// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavYwKTiBArhxf9MSdwZgePREWl__1Zbg',
    appId: '1:648396802759:android:525db9364865c282a24ce2',
    messagingSenderId: '648396802759',
    projectId: 'beslen-b458f',
    storageBucket: 'beslen-b458f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmsnJ9MtAJF26bIG6mzThjki1C4ANynOs',
    appId: '1:648396802759:ios:04da7ed19aa97105a24ce2',
    messagingSenderId: '648396802759',
    projectId: 'beslen-b458f',
    storageBucket: 'beslen-b458f.firebasestorage.app',
    iosBundleId: 'com.example.beslen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmsnJ9MtAJF26bIG6mzThjki1C4ANynOs',
    appId: '1:648396802759:ios:04da7ed19aa97105a24ce2',
    messagingSenderId: '648396802759',
    projectId: 'beslen-b458f',
    storageBucket: 'beslen-b458f.firebasestorage.app',
    iosBundleId: 'com.example.beslen',
  );
}
